# Generated by Django 2.2 on 2020-05-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女'), (2, '保密')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, '超级管理员'), (1, '权限用户'), (2, '普通用户')], default=2),
        ),
    ]
