# Generated by Django 2.2 on 2020-05-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200507_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女'), (2, '保密')], default=0),
        ),
    ]
