# Generated by Django 2.2 on 2020-05-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_permission_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission_list',
            options={'permissions': (('enable_user', '激活用户'), ('disable_user', '禁用用户'), ('reset_password', '重置密码')), 'verbose_name': '附加权限表'},
        ),
    ]
