# Generated by Django 2.2 on 2020-06-02 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任务名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务系统',
                'verbose_name_plural': '任务系统',
                'permissions': (('view_task', '查看任务'), ('add_task', '添加任务'), ('change_task', '编辑任务'), ('delete_task', '删除任务'), ('review_task', '审核任务'), ('release_task', '发布任务'), ('view_history', '查看历史')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HistoricTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='更新内容')),
                ('status', models.IntegerField(choices=[(-1, '已取消'), (0, '待审核'), (1, '未通过'), (2, '待发布'), (3, '已发布')], default=0)),
                ('review_at', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('review_notes', models.CharField(max_length=255, null=True, verbose_name='审核意见')),
                ('publish_at', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('result', models.TextField(null=True, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('apply_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_tasks', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('dest_hosts', models.ManyToManyField(related_name='host_historic_tasks', to='cmdb.Host', verbose_name='上线的主机')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_tasks', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '历史任务',
                'verbose_name_plural': '历史任务',
                'default_permissions': (),
            },
        ),
    ]
