# Generated by Django 2.2 on 2020-04-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_user',
            name='user_type',
            field=models.IntegerField(choices=[(1, '普通用户'), (2, '会员用户'), (3, '超级管理员')], default=1, help_text='用户类型'),
        ),
        migrations.AlterField(
            model_name='project_user',
            name='name',
            field=models.CharField(help_text='姓名', max_length=16),
        ),
    ]
