# Generated by Django 2.2 on 2020-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_user',
            name='age',
            field=models.IntegerField(blank=True, help_text='年龄', null=True),
        ),
        migrations.AlterField(
            model_name='project_user',
            name='phone',
            field=models.IntegerField(blank=True, help_text='手机', null=True),
        ),
    ]
