# Generated by Django 2.2 on 2020-04-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200426_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_user',
            name='phone',
            field=models.CharField(blank=True, help_text='手机', max_length=11, null=True),
        ),
    ]
